### PR TITLE
DM-19852: Add deprecation messages around classes that have moved to pipe_tasks

### PR DESCRIPTION
**Pull request by timj**
I've only added the deprecation message to the two classes that were used by our pipeline code.

### CODE REVIEW

**Review by erykoff — APPROVED** [review]
Technically, I think we can move this to v24 because we're still in the between-23-and-24 period, right?  But this is more conservative.

**Comment by timj** [comment]
v24 is going to be derived from weekly 28 so we've already missed that. We can though request to backport this ticket to v24 (along with the FocalPlaneBackground changes) and kickstart the deprecation period.

**Comment by erykoff** [comment]
Ah, I didn't realize that!  I don't think it's worth the backport trouble.

**Comment by timj** [comment]
I added a backport request in case someone wants to do it.

**Pull request merged**
